aeg-logger:
  transports:
    - type: console
      level: debug
      colorize: false
      timestamp: true
    - type: file
      level: debug
      filename: logs/aeg-logger.log
    - type: paperTrail
      level: debug
      host: logs3.papertrailapp.com
      port: 39168
      program: test
