aeg-logger:
  transports:
    - type: console
      level: debug
    - type: file
      level: debug
      filename: logs/aeg-logger.log
#    - type: paperTrail
#      level: debug
#      host: x
#      port: x
#      program: aeg-logger